---
openapi: 3.0.2
info:
  title: Prova-CROSS
  description: "Descrizione dell'esempio studenti on line, con l'aggiunta degli elementi di CROSS. L'esempio è validato dall'app di Swagger hub. Per questioni di semplicità considereremo solo gli attori Insegnante e Studente"
  version: "Cross3.2.0-oas3"

servers:
  - url: https://almaesami.unibo.it/almaesami/welcome.htm
    description: Ipotizziamo che ci sia un'unico punto di login

paths: #il path per noi rappresenta il concetto

  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/:
    parameters: #necessari quando si usano dei parametri nel path
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: "Valore dell'anno accademico"
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: "Id dell'insegnamento"
        required: true
        schema:
          type: string
    
    
    post:
      summary: crea un nuovo appello per l'insegnamento
      parameters:
        - name: data
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            $ref: "#/components/schemas/simple-string"
        - name: ora
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            $ref: "#/components/schemas/simple-string"
            
        - name: aula
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            $ref: "#/components/schemas/simple-string"
        - name: commissione
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
      tags:
        - ~docente
      x-auto: false
      x-number: 1
      x-default: none #può assumere o il valore none oppure una lista di valori di default
                      #che popolernno i campi nell'ordine in cui sono specificati i parametri
      x-persistent: true
      responses:
        '200':
          description: Messaggio di correttaorretta creazione dell'appello

            
        
          

  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/1234:
    parameters: #necessari quando si usano dei parametri nel path
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: "Valore dell'anno accademico"
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: "Id dell'insegnamento"
        required: true
        schema:
          type: string
          
    get:
      summary: ritorna L'appello dal codice 1234
      tags:
        - ~studente
        - ~docente
      
      responses:
        '200':
          description: Vengono correttamente ritornate tutte le informazioni sull'appello 1234
          #Si omette lo schema dell'oggetto ritornato per questioni di verbosità
    delete:
      summary: Cancella l'istanza 1234 di un appello
      description: >-
        "Cancella l\'istanza 1234 del concetto appello:: se la data dell\'
        appello è posteriore a quella odierna cancella definitivamente, 
        altrimenti archivia. L'archiviazione è automatica"
      tags: 
        - ~docente
      x-auto: true #in caso di archiviazione
      x-cross-case:
        - permanent
        - archiviation
      responses:
        '200':
          description: Notifica l'avvenuta cancellazione
          
  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/ridotta:
    parameters:
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: Valore dell'anno accademico
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: Id dell'insegnamento
        required: true
        schema:
          type: string
  
    get:
      summary: Ritorna la lista degli appelli
      x-collection-case: list
      tags:
        - ~docente
        - ~studente
      responses:
        '200':
          description: >-
            Se chiamata da un docente ritorna gli appelli futuri in cui appare in commissione,
            se chiamata da uno studente ritorna gli appelli futuri degl insegnamenti seguiti
            e non ancora superati
        '204':
          description: >-
            Se chiamata da un docente lo invita a inserire un nuovo appello,
            se chiamata da uno studente lo avvisa dell'assenza di appelli disponibili
      

  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/1234/data:
    parameters:
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: "Valore dell'anno accademico"
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: "Id dell'insegnamento"
        required: true
        schema:
          type: string
    get:
      summary: ritorna la data del'appello dal codice 1234
      tags:
        - ~studente
        - ~docente
      responses:
        '200':
          description: Ritorna una vista ridotta dell'appello 1234
    put:
      summary: modifica la data dell'appello 1234
      tags:
        - ~docente #in questo caso sto dicendo che solo un docente può eseguire questa operazione
                   #se chiamato da altri attori deve ritornare un codice 403
      x-auto: false
      responses:
        '200':
          description: Data modificata per l'appello 1234
        '400':
          description: >-
            "Se si invoca l'operazione su un appello passato
            ritorna errore"
  
  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/1234/listaiscritti/:
    parameters:
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: "Valore dell'anno accademico"
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: "Id dell'insegnamento"
        required: true
        schema:
          type: string
    
    get:
      summary: ritorna la lista deglli iscritti all'appello 123
      tags:
        - ~docente
      x-cross-case: list
      responses:
        '200':
          description: Lista degli studenti iscritti
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

tags: #Gli attori (roles) diventano casi particolari di tag, preceduti dal simbolo tilde '~'
  - name: ~studente
    description: Chiunque sia iscritto a un corso di laurea, laurea magistrale o dottorato
    x-characters: 
      - name: Michel Bellomo
        identikit: "Laureando in Informatica di 25 anni..." #Si omette per ragioni di spazio
        domain: 4
        techincal: 5
        language: 4
        phisical: 3
        motivation: 3
        focus: 1
        scenarios:
         - "Michel vuole prenotare l'appello per il suo ultimo esame..." #Si omette per ragioni di spazio
         - "Michel vuole fare delle proiezioni sulla sua media..."
  - name: ~docente
    description: Chiunque sia o sia stato titolare di un corso. Comprende tutte le categoire
  - name: ~amministrativo
    description: Qualunque impiegato con ruoli di segreteria o contabilità includendo gli operatori dei vari sportelli

#Attenzione ai trattini dopo gli spazi nelle liste, altrimenti il parser implode
components:
  schemas:
    simple-string:
      type: string
      nullable: false
      
  
      


x-navigation:
  autenticazione:
  id: aut
  x-link:
    studente: 
      id: studHome
      content:
        - header:
          description: common header (potrebbe corrispondere allo header html)
        - menu-studente:
          description: Menù dei contenuti dell'interfaccia del role studente
          content:
            - bacheca:
              descritpion: link alla bacheca
              x-link: bac0
            - prenotazioni: 
              id: prenLink
              description: link alle prenotazioni
              x-link:
                prenotazioniPagina:
                  id: pren0
                  descrizione: Pagina per la visualizzazione delle prenotazioni
                  content:
                    - header
                    - lista:
                      description: Lista di appelli prenotati
                    - footer
                  
            - appelli:
              description: link agli appelli
              x-link:
                appelliPagina:
                  content:
                    - header
                    - lista:
                      description: Lista di appelli disponibili
                    - footer
            - bacheca-esiti:
              description: link alla bacheca esiti
              x-link:
                esitiPagina:
                content:
                    - header
                    - lista:
                      description: Lista degli esami sostenuta negli scorsi 7 giorni
                    - footer
            - piano-di-studio:
              description: link al piano di studio
              x-link:
                esitiPagina:
                content:
                    - header:
                    - lista:
                      description: >-
                        "Pagina per la compilazione del piano
                          di studi"
                    - footer
            - statistiche:
              description: Pagina con varie statistiche
              content:
                - grafici
                - proiezioni
        - bacheca:
          description: >-
            "Bacheca riassuntiva dello studente, contiene varie viste sommario"
            content:
              - avvisi:
                id: avvisi
                description: Spazio per una lista di avvisi
                  x-link: avv0
              - appelli:
                id: lookApp
                description: >-
                  "Lookup dei prossimi appelli disponibili con
                  in risalto quelli prenotati"
                x-link: app0
                x-link: pren0
                - media:
                id: media
                description: Spazio con una media
                x-link: stat
        - footer:
          description: Footer con informazioni legali
            
    docente:
      id: docHome
      description: Home page riassuntiva del docente
      content:
        - header:
          description: common header (potrebbe corrispondere allo header html)
        - menu:
          description: menù dei contenuti per il role docente
          content:
            -insegnamenti:
              description: link agli insegnamenti
              x-link:
                insegnamentiPagina:
                  id: ins1
                  description: >-
                    "Pagina con gli insegnamenti del docente, divisi in
                    semestri con in evidenza quelli del semestre. A questi
                    seguono gli insegnamenti non più attivi."
                  content:
                      -header
                      -lista
                      -footer
            -appelli:
              description: link agli appelli
              x-link:
                appelliPagina:
                  id: app1
                  description: >-
                    "Pagina con gli appelli di cui il docente è titolare o
                    in commissione. La pagina permette di creare, cancellare
                    appelli o modificare quelli di cui è presidente.
                    È possibile passare alla visualizzazione di una traccia
                    d'esame."
                  content:
                      -header
                      -lista
                      -footer
            -tracce-esami:
              description: link alle tracce d'esame
              x-link:
                traccePagina:
                  id: trac1
                  description: >-
                    "Pagina con le tracce d'esame. Permette la creazione,
                    la visualizzazione e l'archiviazione di tracce."
                    content:
                      -header
                      -lista
                      -footer
            -lauree:
              description: link alle lauree
              x-link:
                laureePagina:
                  id: laur1
                  description: >-
                    "Pagina per la gestione delle tesi dei laureandi e
                    gli appelli di laurea di cui il docente è in commissione"
                    content:
                      -header
                      -laureandi:
                        description: >-
                          "Permette di visualizzare e approvare le tesi dei
                          laureandi di cui è relatore"
                      -appelli:
                        description: Permette di visualizzare gli appelli in cui è in commissione
                      -footer
            -verbali:
              description: link ai verbali
        - bacheca:
          description: "Contenitore di informazioni con vare viste sommario"
          content:
            -orari-lezioni:
              description: Lookup degli orari degli insegnamenti del semestre
              x-link: ins1
            -appelli:
              description: Lookup dei prossimi appelli di cui il docente è titolare o in commissione
              x-link: app1
            -verbali:
              description: Lookup dei verbali da firmare
              x-link: verb1
        - footer:
          description: Footer con informazioni legali
  
    amministrativo:
      #Si omette per non appesantire l'esempio.
...