---
openapi: 3.0.2
info:
  title: Prova-CROSS
  description: "Descrizione dell'esempio studenti on line, con l'aggiunta degli elementi di CROSS. L'esempio è validato dall'app di Swagger hub. Per questioni di semplicità considereremo solo gli attori Insegnante e Studente"
  version: "Cross3.2.0-oas3"

servers:
  - url: https://almaesami.unibo.it/almaesami/welcome.htm
    description: Ipotizziamo che ci sia un'unico punto di login

paths: #il path per noi rappresenta il concetto

  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/:
    parameters: #necessari quando si usano dei parametri nel path
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: "Valore dell'anno accademico"
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: "Id dell'insegnamento"
        required: true
        schema:
          type: string
          
    post:
      summary: crea un nuovo appello per l'insegnamento
      
      parameters:
        - name: data
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            $ref: "#/components/schemas/simple-string"
        - name: ora
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            $ref: "#/components/schemas/simple-string"
            
        - name: aula
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            $ref: "#/components/schemas/simple-string"
        - name: commissione
          in: query
          description: tags to filter by
          required: false
          style: form
          schema:
            type: array
            items:
              type: string
      tags:
        - ~docente
      x-auto: false
      x-number: 1
      x-default: none #può assumere o il valore none oppure una lista di valori di default
                      #che popolernno i campi nell'ordine in cui sono specificati i parametri
      x-persistent: true
          
      responses:
        '200':
          description: Messaggio di correttaorretta creazione dell'appello
        
          

  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/1234:
    parameters: #necessari quando si usano dei parametri nel path
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: "Valore dell'anno accademico"
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: "Id dell'insegnamento"
        required: true
        schema:
          type: string
          
    get:
      summary: ritorna L'appello dal codice 1234
      tags:
        - ~studente
        - ~docente
      
      responses:
        '200':
          description: Vengono correttamente ritornate tutte le informazioni sull'appello 1234
          #Si omette lo schema dell'oggetto ritornato per questioni di verbosità
    delete:
      summary: Cancella l'istanza 1234 di un appello
      description: >-
        "Cancella l\'istanza 1234 del concetto appello:: se la data dell\'
        appello è posteriore a quella odierna cancella definitivamente, 
        altrimenti archivia. L'archiviazione è automatica"
      tags: 
        - ~docente
      x-auto: true #in caso di archiviazione
      x-cross-case:
        - permanent #se la data è posteriore a quella odierda
        - archiviation #se la data è quella odierna o precedente
        
      responses:
        '200':
          description: Notifica l'avvenuta cancellazione
          
  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/1234/ridotta:
    parameters:
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: Valore dell'anno accademico
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: Id dell'insegnamento
        required: true
        schema:
          type: string
  
    get:
      summary: ritorna L'appello dal codice 1234
      tags:
        - ~studente
        - ~docente
      responses:
        '200':
          description: Ritorna una vista ridotta dell'appello 1234
      

  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/1234/data:
    parameters:
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: "Valore dell'anno accademico"
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: "Id dell'insegnamento"
        required: true
        schema:
          type: string
    get:
      summary: ritorna la data del'appello dal codice 1234
      tags:
        - ~studente
        - ~docente
      responses:
        '200':
          description: Ritorna una vista ridotta dell'appello 1234
    put:
      summary: modifica la data dell'appello 1234
      tags:
        - ~docente #in questo caso sto dicendo che solo un docente può eseguire questa operazione
                   #se chiamato da altri attori deve ritornare un codice 403
      x-auto: false
      responses:
        '200':
          description: Modifica la data dell'appello 1234
        '400':
          description: Nel caso la data non fosse modificabile ritorna un errore
  
  /cds/{corsodistudio}/AY/{2019}/insegnamenti/{codiceins}/appelli/1234/listaiscritti/:
    parameters:
      - name: corsodistudio
        in: path
        description: "Id del corso di studio"
        required: true
        schema:
          type: string
      
      - name: "2019"
        in: path
        description: "Valore dell'anno accademico"
        required: true
        schema:
          type: number
      
      - name: codiceins
        in: path
        description: "Id dell'insegnamento"
        required: true
        schema:
          type: string
    
    get:
      summary: ritorna la lista degli appelli disponibili
      tags:
        - ~studente
        - ~docente
      x-cross-case: list
      responses:
        '200':
          description: ritorna gli appelli disponibili di tutti gli esami
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

tags: #Gli attori (roles) diventano casi particolari di tag, preceduti dal simbolo tilde '~'
  - name: ~studente
    description: Chiunque sia iscritto a un corso di laurea, laurea magistrale o dottorato
  - name: ~docente
    description: Chiunque sia o sia stato titolare di un corso. Comprende tutte le categoire
  - name: ~amministrativo
    description: Qualunque impiegato con ruoli di segreteria o contabilità includendo gli operatori dei vari sportelli

#Attenzione ai trattini dopo gli spazi nelle liste, altrimenti il parser implode
components:
  schemas:
    simple-string:
      type: string
      nullable: false
      
  x-navigation:
    menu-studente:
      id: "men0"
      description: "Menù dei contenuti dell'interfaccia del role studente"
      content:
        - riepilogo
        - prenotazioni
        - bacheca-esiti
        - piano-di-studio
        - statistiche

#in questi campi privati non vuole che metta $ref o commenti di alcun ché, bisogna trovare un workaround
x-navigation:
  autenticazione:
  
    studente: 
      - header:
        id: xk1
        description: common header (potrebbe corrispondere allo header html)
        
      - $ref: "#/components/x-navigation/menu-studente"
      - avvisi
      - footer
      - nome
    insegnante:
      - header
      - menu
      - calendario
      - footer
    amministrativo:
      #Si omette per ragioni di verbosità
...